#####
## Pins
#####

# Timing Constraint
#Primary Clocks
create_clock -period 3.367 -name HDMI_RX_CLK_P_IN -waveform {0.000 1.684} -add [get_ports HDMI_RX_CLK_P_IN]
create_clock -period 3.367 -name TX_REFCLK_P_IN -waveform {0.000 1.684} -add [get_ports TX_REFCLK_P_IN]

# System Clock
#ACLK1
set_property PACKAGE_PIN F35 [get_ports CLK_IN1_D_clk_p]
set_property IOSTANDARD LVDS [get_ports CLK_IN1_D_clk_p]

#IIC CTL
#A[4]
set_property PACKAGE_PIN BF32 [get_ports HDMI_CTL_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CTL_scl_io]
#A[5]
set_property PACKAGE_PIN BF31 [get_ports HDMI_CTL_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CTL_sda_io]

# Si5324C
#MGT221
set_property PACKAGE_PIN BU10 [get_ports TX_REFCLK_N_IN]
set_property PACKAGE_PIN BU11 [get_ports TX_REFCLK_P_IN]
#D[0]
set_property PACKAGE_PIN BL31 [get_ports RX_REFCLK_P_OUT]
set_property IOSTANDARD LVDS [get_ports RX_REFCLK_P_OUT]
#B[11]
set_property PACKAGE_PIN BG31 [get_ports HDMI_Si5324C_LOL_IN]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_Si5324C_LOL_IN]

# HDMI RX
# TMDS181I
#MGT221
set_property PACKAGE_PIN BW10 [get_ports HDMI_RX_CLK_N_IN]
set_property PACKAGE_PIN BW11 [get_ports HDMI_RX_CLK_P_IN]
#A[11]
set_property PACKAGE_PIN BF34 [get_ports RX_HPD_OUT]
set_property IOSTANDARD LVCMOS18 [get_ports RX_HPD_OUT]

# TPD4E05U06DQA
#A[2]
set_property PACKAGE_PIN BE33 [get_ports RX_DET_IN]
set_property IOSTANDARD LVCMOS18 [get_ports RX_DET_IN]
#A[0]
set_property PACKAGE_PIN BJ33 [get_ports RX_DDC_OUT_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports RX_DDC_OUT_scl_io]
#A[1]
set_property PACKAGE_PIN BK33 [get_ports RX_DDC_OUT_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports RX_DDC_OUT_sda_io]

# HDMI TX
# SN65DP159
#MGT221
set_property PACKAGE_PIN BT4 [get_ports {HDMI_RX_DAT_P_IN[0]}]
set_property PACKAGE_PIN BV9 [get_ports {HDMI_TX_DAT_P_OUT[0]}]
set_property PACKAGE_PIN BR2 [get_ports {HDMI_RX_DAT_P_IN[1]}]
set_property PACKAGE_PIN BU7 [get_ports {HDMI_TX_DAT_P_OUT[1]}]
set_property PACKAGE_PIN BP4 [get_ports {HDMI_RX_DAT_P_IN[2]}]
set_property PACKAGE_PIN BT9 [get_ports {HDMI_TX_DAT_P_OUT[2]}]
#C[0]
set_property PACKAGE_PIN BL32 [get_ports HDMI_TX_CLK_P_OUT]
set_property IOSTANDARD LVDS [get_ports HDMI_TX_CLK_P_OUT]
#A[8]
set_property PACKAGE_PIN BE30 [get_ports TX_DDC_OUT_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports TX_DDC_OUT_scl_io]
#A[9]
set_property PACKAGE_PIN BE29 [get_ports TX_DDC_OUT_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports TX_DDC_OUT_sda_io]
#C[10]
set_property PACKAGE_PIN BR34 [get_ports {TX_EN_OUT[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TX_EN_OUT[0]}]
# TPD12S016
#A[6]
set_property PACKAGE_PIN BG34 [get_ports TX_HPD_IN]
set_property IOSTANDARD LVCMOS18 [get_ports TX_HPD_IN]

# UART
set_property PACKAGE_PIN BT31 [get_ports UART_rxd]
set_property PACKAGE_PIN BU31 [get_ports UART_txd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports UART_txd]

# cec
set_property PACKAGE_PIN BE32 [get_ports cec]
set_property IOSTANDARD LVCMOS18 [get_ports cec]

# ILA
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]

#ddr4
set_property PACKAGE_PIN AV55 [get_ports {ddr4ht3_refclk_en_n[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ddr4ht3_refclk_en_n[0]}]
set_property PACKAGE_PIN BJ63 [get_ports {C0_DDR4_dq[0]}]
set_property PACKAGE_PIN BJ61 [get_ports {C0_DDR4_dq[1]}]
set_property PACKAGE_PIN BH59 [get_ports {C0_DDR4_dq[2]}]
set_property PACKAGE_PIN BH60 [get_ports {C0_DDR4_dq[3]}]
set_property PACKAGE_PIN BJ62 [get_ports {C0_DDR4_dq[4]}]
set_property PACKAGE_PIN BG59 [get_ports {C0_DDR4_dq[5]}]
set_property PACKAGE_PIN BH61 [get_ports {C0_DDR4_dq[6]}]
set_property PACKAGE_PIN BJ60 [get_ports {C0_DDR4_dq[7]}]
set_property PACKAGE_PIN BD62 [get_ports {C0_DDR4_dq[8]}]
set_property PACKAGE_PIN BE62 [get_ports {C0_DDR4_dq[9]}]
set_property PACKAGE_PIN BD63 [get_ports {C0_DDR4_dq[10]}]
set_property PACKAGE_PIN BE59 [get_ports {C0_DDR4_dq[11]}]
set_property PACKAGE_PIN BE63 [get_ports {C0_DDR4_dq[12]}]
set_property PACKAGE_PIN BF59 [get_ports {C0_DDR4_dq[13]}]
set_property PACKAGE_PIN BE60 [get_ports {C0_DDR4_dq[14]}]
set_property PACKAGE_PIN BF60 [get_ports {C0_DDR4_dq[15]}]
set_property PACKAGE_PIN BC60 [get_ports {C0_DDR4_dq[16]}]
set_property PACKAGE_PIN BC59 [get_ports {C0_DDR4_dq[17]}]
set_property PACKAGE_PIN BB63 [get_ports {C0_DDR4_dq[18]}]
set_property PACKAGE_PIN BC63 [get_ports {C0_DDR4_dq[19]}]
set_property PACKAGE_PIN BC58 [get_ports {C0_DDR4_dq[20]}]
set_property PACKAGE_PIN BD60 [get_ports {C0_DDR4_dq[21]}]
set_property PACKAGE_PIN BA62 [get_ports {C0_DDR4_dq[22]}]
set_property PACKAGE_PIN BB62 [get_ports {C0_DDR4_dq[23]}]
set_property PACKAGE_PIN AW62 [get_ports {C0_DDR4_dq[24]}]
set_property PACKAGE_PIN AY62 [get_ports {C0_DDR4_dq[25]}]
set_property PACKAGE_PIN AW60 [get_ports {C0_DDR4_dq[26]}]
set_property PACKAGE_PIN AY60 [get_ports {C0_DDR4_dq[27]}]
set_property PACKAGE_PIN AY59 [get_ports {C0_DDR4_dq[28]}]
set_property PACKAGE_PIN BA59 [get_ports {C0_DDR4_dq[29]}]
set_property PACKAGE_PIN AV63 [get_ports {C0_DDR4_dq[30]}]
set_property PACKAGE_PIN AW63 [get_ports {C0_DDR4_dq[31]}]
set_property PACKAGE_PIN AW58 [get_ports {C0_DDR4_dq[33]}]
set_property PACKAGE_PIN BC55 [get_ports {C0_DDR4_dq[34]}]
set_property PACKAGE_PIN AW57 [get_ports {C0_DDR4_dq[32]}]
set_property PACKAGE_PIN BC56 [get_ports {C0_DDR4_dq[35]}]
set_property PACKAGE_PIN BB56 [get_ports {C0_DDR4_dq[36]}]
set_property PACKAGE_PIN BB57 [get_ports {C0_DDR4_dq[37]}]
set_property PACKAGE_PIN AY57 [get_ports {C0_DDR4_dq[38]}]
set_property PACKAGE_PIN BA57 [get_ports {C0_DDR4_dq[39]}]
set_property PACKAGE_PIN AU56 [get_ports {C0_DDR4_dq[40]}]
set_property PACKAGE_PIN AU57 [get_ports {C0_DDR4_dq[41]}]
set_property PACKAGE_PIN AP55 [get_ports {C0_DDR4_dq[42]}]
set_property PACKAGE_PIN AP56 [get_ports {C0_DDR4_dq[43]}]
set_property PACKAGE_PIN AR54 [get_ports {C0_DDR4_dq[44]}]
set_property PACKAGE_PIN AR55 [get_ports {C0_DDR4_dq[45]}]
set_property PACKAGE_PIN AT54 [get_ports {C0_DDR4_dq[46]}]
set_property PACKAGE_PIN AT55 [get_ports {C0_DDR4_dq[47]}]
set_property PACKAGE_PIN AU51 [get_ports {C0_DDR4_dq[48]}]
set_property PACKAGE_PIN AT52 [get_ports {C0_DDR4_dq[49]}]
set_property PACKAGE_PIN AT51 [get_ports {C0_DDR4_dq[50]}]
set_property PACKAGE_PIN AU52 [get_ports {C0_DDR4_dq[51]}]
set_property PACKAGE_PIN AP52 [get_ports {C0_DDR4_dq[52]}]
set_property PACKAGE_PIN AP53 [get_ports {C0_DDR4_dq[53]}]
set_property PACKAGE_PIN AR52 [get_ports {C0_DDR4_dq[54]}]
set_property PACKAGE_PIN AR53 [get_ports {C0_DDR4_dq[55]}]
set_property PACKAGE_PIN AV49 [get_ports {C0_DDR4_dq[56]}]
set_property PACKAGE_PIN AP48 [get_ports {C0_DDR4_dq[57]}]
set_property PACKAGE_PIN AV50 [get_ports {C0_DDR4_dq[58]}]
set_property PACKAGE_PIN AV51 [get_ports {C0_DDR4_dq[59]}]
set_property PACKAGE_PIN AP47 [get_ports {C0_DDR4_dq[60]}]
set_property PACKAGE_PIN AU49 [get_ports {C0_DDR4_dq[61]}]
set_property PACKAGE_PIN AR49 [get_ports {C0_DDR4_dq[62]}]
set_property PACKAGE_PIN AR50 [get_ports {C0_DDR4_dq[63]}]

set_property PACKAGE_PIN AT44 [get_ports {C0_DDR4_dq[64]}]
set_property PACKAGE_PIN AT45 [get_ports {C0_DDR4_dq[65]}]
set_property PACKAGE_PIN AU46 [get_ports {C0_DDR4_dq[66]}]
set_property PACKAGE_PIN AU47 [get_ports {C0_DDR4_dq[67]}]
set_property PACKAGE_PIN AV45 [get_ports {C0_DDR4_dq[68]}]
set_property PACKAGE_PIN AV46 [get_ports {C0_DDR4_dq[69]}]
set_property PACKAGE_PIN AP45 [get_ports {C0_DDR4_dq[70]}]
set_property PACKAGE_PIN AP46 [get_ports {C0_DDR4_dq[71]}]
set_property PACKAGE_PIN BB47 [get_ports {C0_DDR4_adr[0]}]
set_property PACKAGE_PIN BB48 [get_ports {C0_DDR4_adr[1]}]
set_property PACKAGE_PIN BA46 [get_ports {C0_DDR4_adr[2]}]
set_property PACKAGE_PIN BB46 [get_ports {C0_DDR4_adr[3]}]
set_property PACKAGE_PIN AW46 [get_ports {C0_DDR4_adr[4]}]
set_property PACKAGE_PIN AW47 [get_ports {C0_DDR4_adr[5]}]
set_property PACKAGE_PIN AW48 [get_ports {C0_DDR4_adr[6]}]
set_property PACKAGE_PIN AY48 [get_ports {C0_DDR4_adr[7]}]
set_property PACKAGE_PIN AW45 [get_ports {C0_DDR4_adr[8]}]
set_property PACKAGE_PIN AY45 [get_ports {C0_DDR4_adr[9]}]
set_property PACKAGE_PIN AW50 [get_ports {C0_DDR4_adr[10]}]
set_property PACKAGE_PIN AW51 [get_ports {C0_DDR4_adr[11]}]
set_property PACKAGE_PIN BA49 [get_ports {C0_DDR4_adr[12]}]
set_property PACKAGE_PIN BB49 [get_ports {C0_DDR4_adr[13]}]
set_property PACKAGE_PIN BC48 [get_ports {C0_DDR4_adr[14]}]
set_property PACKAGE_PIN BC49 [get_ports {C0_DDR4_adr[15]}]
set_property PACKAGE_PIN BC50 [get_ports {C0_DDR4_adr[16]}]
set_property PACKAGE_PIN BG61 [get_ports {C0_DDR4_dqs_t[0]}]
set_property PACKAGE_PIN BD58 [get_ports {C0_DDR4_dqs_t[1]}]
set_property PACKAGE_PIN BB58 [get_ports {C0_DDR4_dqs_t[2]}]
set_property PACKAGE_PIN AV61 [get_ports {C0_DDR4_dqs_t[3]}]
set_property PACKAGE_PIN AV56 [get_ports {C0_DDR4_dqs_t[4]}]
set_property PACKAGE_PIN AT56 [get_ports {C0_DDR4_dqs_t[5]}]
set_property PACKAGE_PIN AP50 [get_ports {C0_DDR4_dqs_t[6]}]
set_property PACKAGE_PIN AU48 [get_ports {C0_DDR4_dqs_t[7]}]
set_property PACKAGE_PIN AR44 [get_ports {C0_DDR4_dqs_t[8]}]
set_property PACKAGE_PIN BG58 [get_ports {C0_DDR4_dm_n[0]}]
set_property PACKAGE_PIN BF61 [get_ports {C0_DDR4_dm_n[1]}]
set_property PACKAGE_PIN BC61 [get_ports {C0_DDR4_dm_n[2]}]
set_property PACKAGE_PIN BA60 [get_ports {C0_DDR4_dm_n[3]}]
set_property PACKAGE_PIN BA55 [get_ports {C0_DDR4_dm_n[4]}]
set_property PACKAGE_PIN AV54 [get_ports {C0_DDR4_dm_n[5]}]
set_property PACKAGE_PIN AU53 [get_ports {C0_DDR4_dm_n[6]}]
set_property PACKAGE_PIN AT49 [get_ports {C0_DDR4_dm_n[7]}]
set_property PACKAGE_PIN AR47 [get_ports {C0_DDR4_dm_n[8]}]
set_property PACKAGE_PIN BC51 [get_ports {C0_DDR4_ba[0]}]
set_property PACKAGE_PIN BA51 [get_ports {C0_DDR4_ba[1]}]
set_property PACKAGE_PIN BB51 [get_ports {C0_DDR4_bg[0]}]
set_property PACKAGE_PIN AY50 [get_ports {C0_DDR4_bg[1]}]
set_property PACKAGE_PIN AY47 [get_ports {C0_DDR4_ck_t[0]}]
set_property PACKAGE_PIN BA54 [get_ports {C0_DDR4_cke[0]}]
set_property PACKAGE_PIN AY54 [get_ports {C0_DDR4_cke[1]}]
set_property PACKAGE_PIN BA50 [get_ports {C0_DDR4_cs_n[0]}]
set_property PACKAGE_PIN AW53 [get_ports {C0_DDR4_cs_n[1]}]
set_property PACKAGE_PIN AY52 [get_ports {C0_DDR4_odt[0]}]
set_property PACKAGE_PIN BC54 [get_ports {C0_DDR4_odt[1]}]
set_property PACKAGE_PIN BA56 [get_ports C0_DDR4_act_n]
set_property PACKAGE_PIN AY53 [get_ports C0_DDR4_par]
set_property PACKAGE_PIN BA61 [get_ports C0_DDR4_reset_n]
set_property PACKAGE_PIN BA52 [get_ports C0_SYS_CLK_0_clk_p]
#####
## End
#####





set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
connect_debug_port dbg_hub/clk [get_nets exdes_i/clk_wiz_0/clk_out2]
